### ISSUE TITLE
Tixte token error

### ISSUE THREAD

**Issue by sdv75** [DeadNews/images-upload-cli#178]
Hello. On the tixte.com I have ERROR Client error '401 Unauthorized' for url 'https://api.tixte.com/v1/upload'. I use client secret as token. Maybe this is the wrong token? Where can I get the correct token?
![Screenshot_1](https://github.com/DeadNews/images-upload-cli/assets/29115423/e82f010d-8c06-4892-bcbe-02368066ffc1)

**Comment by DeadNews** [comment]
https://tixte.com/dashboard/integrations

```
Integrations

Upload Key: *** Copy
```

**Comment by sdv75** [comment]
Thank you. And what about ptpimg. Can you tell me where I can find this code?
![Screenshot_1](https://github.com/DeadNews/images-upload-cli/assets/29115423/9c2a4ce0-7c4d-4d22-887f-d771155507b7)

**Comment by DeadNews** [comment]
* https://tixte.com/dashboard/domains — try adding a domain.
* https://www.reddit.com/r/trackers/comments/16qf7n4/comment/k1wna10/?context=3

**Comment by sdv75** [comment]
Thank you. tixte work after I added a domain. 
I've read Reddit post before but I don't understand where can I find  /ptpimg.php page?
What domain should I look for it on? 
I don't have an account on the passthepopcorn.me.

**Comment by DeadNews** [comment]
Then you should not have access.
