### ISSUE TITLE
Support Chevereto

### ISSUE THREAD

**Issue by rodber** [DeadNews/images-upload-cli#185]
Hello,

Imgbb and many other services are based on Chevereto (self-hosted image hosting). You can find the API docs here: https://v4-docs.chevereto.com/developer/api/api-v1.html

If you support Chevereto you will be broaden your user market by about 10,000 websites.

**Comment by DeadNews** [comment]
Duplicate: https://github.com/DeadNews/images-upload-cli/issues/32

**Comment by DeadNews** [comment]
> about 10,000 websites.

Name working hosts with open api.

**Comment by rodber** [comment]
Ok good luck.
