### ISSUE TITLE
[REQ] imgbox.com support

### ISSUE THREAD

**Issue by Rofii** [DeadNews/images-upload-cli#23]
If you had time, I'd be very thankful. :)

**Comment by DeadNews** [comment]
I didn't find the documentation for the API.
I don't understand how it's supposed to work.

```py
def test_upload(img: bytes) -> str:
    response = post(
        url="https://imgbox.com/upload/process",
        headers={"X-CSRF-Token": "bOBg1xLf8EoX1Qu8MBwfQ2P6q8g2d5TWK9PS7X1wyOo"},
        cookies={
            "Cookie": "TVNuWEczellUbzBkNU10dFh0Z01RNXB2NDc0bjJFVjVOQXp0K2VMenBFQk1ydWpRd0VVZGRlcEZoaEpYSUxHSzYzWkF1U0NPTTRXR2tDaURkemJycEIvNGRaSHdqaDNMNHNpRzRUT2RjcWt6RlFJb0hKZ3NUQXJTakZSUmp2bER2SCsyaFZsaC85Z2JPMlNjUmNYMzVvQmdWTHRTYnhUNENBWTR2UFhCbU5NSTYxOUxRRkRCeURoRzZlRnF2NEczLS1ReTdISVV6a3RJbS9mQTF0d3NKbGVnPT0%3D--62c662c8b72fe664881ee3cf8ff16983d1b8ce1d"
        },
        data={
            "token_id": 776515365,
            "token_secret": "LtZIWsrzrdOvMKCw",
            "content_type": 2,
            "thumbnail_size": "100c",
        },
        files={"files[]": img},
    )

    if not response.ok:
        raise UploadError(response.text)

    return f"{response.json()['files']}"
```

The only response I get is:
> We're sorry, but something went wrong (500)

**Comment by DeadNews** [comment]
What is the advantage of imgbox?
There are many services with a stable and documented api.
Imgbox api is undocumented. And it is difficult to call it stable: you need to get Token and Cookie by parsing a web page.

**Comment by DeadNews** [comment]
What is the advantage of imgbox?
There are many services with a stable and documented api.
Imgbox api is undocumented. And it is difficult to call it stable: you need to get Token and Cookie by parsing a web page...

**Comment by DeadNews** [comment]
What is the advantage of imgbox?
There are many services with a stable and documented api.
Imgbox api is undocumented. And it is difficult to call it stable: you need to get Token and Cookie by parsing the imgbox.com page...

**Comment by DeadNews** [comment]
What is the advantage of imgbox?
There are many services with a stable and documented api.
Imgbox api is undocumented. And it is difficult to call it stable: you need to get Token and Cookie by parsing imgbox.com page...

**Comment by Rofii** [comment]
> What is the advantage of imgbox? There are many services with a stable and documented api. Imgbox api is undocumented. And it is difficult to call it stable: you need to get Token and Cookie by parsing imgbox.com page...

A site I'm using the links on only has a few whitelisted hosts. Of the many sites your tool already supports, sadly this site only allows ptpimg and imgur. I was uploading many images per day so imgur ended up throttling my IP. Ptpimg is working fine with no throttling so far, but I was hoping to have another backup host.

It seems like it might be more trouble than it's worth though. I assumed it'd be fairly trivial to add it, but I wasn't aware of the state of the imgbox API. Thank you for looking into it though.
