### ISSUE TITLE
Chevereto API

### ISSUE THREAD

**Issue by rodber** [DeadNews/images-upload-cli#32]
Hey @DeadNews 

I noticed that this project supports ImgBB API. Did you know that imgbb is based on Chevereto? If you support Chevereto there will be a lot of potential users for this repo.

To support the Chevereto API is easy as change the URL (enable the user to provide the URL). Everything else is already made, the API is compatible.

Here, check the docs: https://v4-docs.chevereto.com/developer/api/api-v1.html

**Comment by DeadNews** [comment]
1. How many working instances are there with an open api, is there a list? I only found one:

```python
def imgsco_upload(img: bytes) -> str:
    key = "fhadliajlfaddfFdadfidjfladfIfjlakd"

    response = post(
        url="https://imgs.co/api/1/upload",
        data={"key": key},
        files={"source": img},
    )
    if not response.ok:
        raise UploadError(response.json())

    return response.json()["image"]["url"]
```

2. If you can't get the link when image loaded correctly == the api doesn't work.

> {'status_code': 400, 'error': {'message': 'Duplicated upload', 'code': 101}, 'status_txt': 'Bad Request'}

In this case the existing link should be displayed. For example:

https://github.com/DeadNews/images-upload-cli/blob/b57dae3190fddedbdc85b160ee6cd69065950036/src/images_upload_cli/upload.py#L229-L233

**Comment by rodber** [comment]
1. None. Is up to each instance if the API is public or not. We don't keep a registry.

2. Duplicated upload is triggered by IP + time basis. In any case, for us duplicated content doesn't mean duplicated tenency. We won't return existing files as we consider each upload unique.

**Comment by DeadNews** [comment]
I won't add hosts that don't return links.

**Comment by rodber** [comment]
Filo, metete tu wea en la raja
